# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/remoteipy',
                'doc_host': 'https://achalpandeyy.github.io',
                'git_url': 'https://github.com/achalpandeyy/remoteipy',
                'lib_path': 'remoteipy'},
  'syms': { 'remoteipy.core': { 'remoteipy.core.Client': ('core.html#client', 'remoteipy/core.py'),
                                'remoteipy.core.connect': ('core.html#connect', 'remoteipy/core.py'),
                                'remoteipy.core.disconnect': ('core.html#disconnect', 'remoteipy/core.py'),
                                'remoteipy.core.run_remote_blocking': ('core.html#run_remote_blocking', 'remoteipy/core.py')}}}
